version: '3.5'
services:
  ngrok:
    # image: mjourard/ngrok-docker-ssm:latest
    build: .
    ports:
      - 4040:4040
    environment:      
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-'us-east-2'}
      - SSM_PREFIX=/ngrok_apps/${STAGE}/${DEVELOPER}
    volumes:
      - ./ngrok-conf:/ngrok/.ngrok2
  
